### ISSUE TITLE
Missing GTP Echo response on 1.5.2 / 1.6 generates release with transport-resource-unavailable cause

### ISSUE THREAD

**Issue by joary** [magma/magma#9049]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** 1.5.2 & 1.6
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** GTP Flow
- **Deployment Environment:** affects all

### Describe the Issue

Huawei eNB requests a ContextReleaseRequest with cause transport-resource-unavailable after no response for an GTP Echo request.

![image](https://user-images.githubusercontent.com/1166157/132857761-bb38977a-c740-45e1-8e5c-e8cb6a094935.png)

**Comment by joary** [comment]
This should be fixed by default in 1.7, the current solution for 1.6 is:

1. From an 1.6.0 AGW, assure the magma is updated with: `apt upgrade magma`
1.2. Check if the package is up to date with `apt policy magma`, Installed value should something like:  `1.6.0-1625592603-1f26ba81`
2. Update OVS to the latest build using `/usr/local/bin/ovs-kmod-upgrade.sh` 
2.1 If necessary check if the ovs packages were updated with `dpkg --list | grep openvs` all the pacakges should be in `2.15.2-1` version
3. Make sure your `/etc/magma/spgw.yml` has the configuration `ovs_gtpu_echo_resp: true`
4. Restart magma services

**Comment by javieraubert** [comment]
Hi Joary, 

We've followed the instrucciones above, all packages are on the correct versions according to the instructions, however we still don't have an echo response.

![imagen](https://user-images.githubusercontent.com/90400693/132910197-cf256c16-c33e-4b73-a8ac-19a7be6bcb17.png)
![imagen](https://user-images.githubusercontent.com/90400693/132910282-c082978c-be7b-455a-a65d-f396588c6c3c.png)
![imagen](https://user-images.githubusercontent.com/90400693/132910923-2c88a74f-9af2-4c0f-bb76-1889c89dbff3.png)

[10092021.zip](https://github.com/magma/magma/files/7146127/10092021.zip)

**Comment by joary** [comment]
@javieraubert , can you share which kernel are running in this AGW? `uname -a`

**Comment by javieraubert** [comment]
Linux gw2-3 5.4.0-84-generic #94-Ubuntu SMP Thu Aug 26 20:27:37 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by pshelar** [comment]
@javieraubert what is output of `sudo ovs-vsctl show` from the agw

**Comment by javieraubert** [comment]
Hi @pshelar 

751fb615-86fd-4259-80a8-ab75b133fe1d
    Manager "ptcp:6640"
    Bridge gtp_br0
        Controller "tcp:127.0.0.1:6633"
            is_connected: true
        Controller "tcp:127.0.0.1:6654"
            is_connected: true
        fail_mode: secure
        Port gtp_br0
            Interface gtp_br0
                type: internal
        Port g_491ca0a
            Interface g_491ca0a
                type: gtpu
                options: {key=flow, remote_ip="10.202.145.4"}
        Port ipfix0
            Interface ipfix0
                type: internal
        Port li_port
            Interface li_port
                type: internal
        Port proxy_port
            Interface proxy_port
        Port mtr0
            Interface mtr0
                type: internal
        Port patch-up
            Interface patch-up
                type: patch
                options: {peer=patch-agw}
        Port gtp0
            Interface gtp0
                type: gtp
                options: {key=flow, remote_ip=flow}
                error: "could not open network device gtp0 (Address family not supported by protocol)"
        Port g_58dca0a
            Interface g_58dca0a
                type: gtpu
                options: {key=flow, remote_ip="10.202.141.5"}
    Bridge uplink_br0
        Port vlan_pop_in
            Interface vlan_pop_in
        Port eth1
            Interface eth1
        Port dhcp0
            Interface dhcp0
                type: internal
        Port vlan_pop_out
            Interface vlan_pop_out
        Port patch-agw
            Interface patch-agw
                type: patch
                options: {peer=patch-up}
        Port uplink_br0
            Interface uplink_br0
                type: internal
    ovs_version: "2.15.2"

**Comment by pshelar** [comment]
can you set `ovs_gtpu_echo_resp` to `true` in '/etc/magma/spgw.yml' and run `config_stateless_agw.py flushall_redis`
After this UE needs to re-attach.

**Comment by javieraubert** [comment]
Hi @pshelar i did it, but same result, still no echo response, i'm taking a full S1 capture, i'll upload it soon.

**Comment by pshelar** [comment]
@javieraubert lets see if it is enabled or not: what is output of `sudo ovs-vsctl show`

**Comment by javieraubert** [comment]
Hi @pshelar 
~# sudo ovs-vsctl show
751fb615-86fd-4259-80a8-ab75b133fe1d
    Manager "ptcp:6640"
    Bridge uplink_br0
        Port vlan_pop_out
            Interface vlan_pop_out
        Port uplink_br0
            Interface uplink_br0
                type: internal
        Port vlan_pop_in
            Interface vlan_pop_in
        Port eth1
            Interface eth1
        Port dhcp0
            Interface dhcp0
                type: internal
        Port patch-agw
            Interface patch-agw
                type: patch
                options: {peer=patch-up}
    Bridge gtp_br0
        Controller "tcp:127.0.0.1:6654"
            is_connected: true
        Controller "tcp:127.0.0.1:6633"
            is_connected: true
        fail_mode: secure
        Port gtp_br0
            Interface gtp_br0
                type: internal
        Port gtp0
            Interface gtp0
                type: gtp
                options: {key=flow, remote_ip=flow}
                error: "could not open network device gtp0 (Address family not supported by protocol)"
        Port li_port
            Interface li_port
                type: internal
        Port proxy_port
            Interface proxy_port
        Port patch-up
            Interface patch-up
                type: patch
                options: {peer=patch-agw}
        Port g_491ca0a
            Interface g_491ca0a
                type: gtpu
                options: {key=flow, remote_ip="10.202.145.4"}
        Port mtr0
            Interface mtr0
                type: internal
        Port ipfix0
            Interface ipfix0
                type: internal
        Port g_58dca0a
            Interface g_58dca0a
                type: gtpu
                options: {key=flow, remote_ip="10.202.141.5"}
    ovs_version: "2.15.2"

**Comment by javieraubert** [comment]
@joary and @pshelar, here is a link to download a capture from S1 interface

https://drive.google.com/drive/folders/1XGWYvh8rjf_BGBp90RqlnGfOtmHEHs_w?usp=sharing

**Comment by pshelar** [comment]
Actually, GTP echo is still not supported in 1.6.0 release. It was backported to 1.6 after the release.

**Comment by javieraubert** [comment]
@pshelar this version: 1.6.0-1625592603-1f26ba81 still does not support the GTP echo??

**Comment by pshelar** [comment]
not really.

**Comment by joary** [comment]
@javieraubert , you can find a build that includes the GTPU solution in the following link, made from commit (b7ab42d52532df72192a9a69882a2274218d571b)

https://www.dropbox.com/s/bhwehfidf1wfx8s/magma-packages-1.6.zip?dl=0

**Comment by javieraubert** [comment]
Hi @joary and @pshelar we installed the packages and it is sending the GTPU response. Now we do not have the transport-resource unavailable message.

**Comment by pshelar** [comment]
GTP echo response feature would be available in release 1.7.

**Comment by crbertoldo** [comment]
@joary is it a blocker for Huawei eNB integration?

**Comment by crbertoldo** [comment]
Hi @javieraubert did you manage to solve this issue?

**Comment by javieraubert** [comment]
Hi @crbertoldo we have compiled a version of the master.
